# Data Science Tools and Ecosystem

In this notebook, Data Science Tools and Ecosystem are summarized.

Objecttives:
- Python
- R
- SQL
- C++
- Java

Some of the popular languages that Data Scientists use are:
1. Python
2. R
3. SQL
4. C++

Some of the commonly used libraries used by Data Scientists include:
1. Pandas
2. Numpy
3. Karas
4. Plotly

| Data Science Tools|
| ----------------- |
| Jupyter Notebook  |
| Rstudio           |
| Visual Studio     |

### Below are a few examples of evaluating arithmetic expressions in Python

In [7]:
>>> eval("2 * 8")

16

In [8]:
>>> x = 50
>>> eval("x * 4")

200

In [9]:
>>> eval("sum([4, 9, 1])")

14

In [22]:
 # This a simple arithmetic expression to mutiply then add integers

 eval("((3*4)+5)")

17

In [1]:
#  This will convert 200 minutes to hours by diving by 60.
h=200//60
print("Hours=",h)

Hours= 3

## Author
Daniel Abora